### ISSUE TITLE
Setting a durability for ANCIENT_DEBRIS or NETHERITE_BLOCK doesn't work

### ISSUE THREAD

**Issue by Adveragejoe** [SirLeezus/CrackedBlocks#1]
When you set a durability for either ANCIENT_DEBRIS or NETHERITE_BLOCK, you can see the durability for the blocks using the durability checker tool, but the durability never goes down and you can't break the blocks with tnt.

Pastebin of config: https://pastebin.com/edKkQ777

Video example (may still need time to process): https://drive.google.com/file/d/1UY7OIDY4ms5ZaZ8OhpA93GvGIRI6zJsK/view?usp=sharing

Thanks! :D

**Comment by LeeTheTech** [comment]
Should be fixed on 1.0.2! Thanks for reporting!
