### ISSUE TITLE
the location of a blocks durability doesn't reset when manually replaced

### ISSUE THREAD

**Issue by Adveragejoe** [SirLeezus/CrackedBlocks#2]
If you place a block with a set durability, blast it with tnt to lower the durability without destroying it, then manually break the block and replace it the durability still says -1/full.

Pastebin of config: https://pastebin.com/Gsy81Zui

Example video (may still be processing): https://drive.google.com/file/d/1aOJR39i87_5VYto9tYeA17qJe2BzXMZB/view?usp=sharing

Thanks! :D

**Comment by LeeTheTech** [comment]
Should be fixed on 1.0.2! Thanks for reporting!
