### ISSUE TITLE
WorldGuard Flag

### ISSUE THREAD

**Issue by Thetduong** [SirLeezus/CrackedBlocks#3]
Players using throwable creepers and creeper eggs at spawn and it blows up block's that have a durability on it. 

Also with faction claims too (warzone/safezone)

**Comment by LeeTheTech** [comment]
I'll need to add direct support for those plugins, when I find some time I'll push an update for that!

**Comment by LeeTheTech** [comment]
Try the latest version, should check if the explosion is canceled now.
