### ISSUE TITLE
Obsidian not destroying from TNT

### ISSUE THREAD

**Issue by MrButtermaker** [SirLeezus/CrackedBlocks#4]
This is an extension from the one on Spigot, but basically I downloaded the plugin earlier today and I was testing its features and basically the Obsidian isn't being destroyed from the TNT even though the durability is in the negatives (-7/3). Im on 1.8.8 as well, but besides this issue with the Obsidian, everything else seems fine (I havnt tried the water tho). Plus I looked into the config and settings and I couldn't find anything about this issue, which is why i made this.

**Comment by LeeTheTech** [comment]
That's odd, I'll have to boot a test server with 1.8.8 and test it. Are you getting any errors when it goes negative?

**Comment by Maylander0808** [comment]
I'm experiencing the same problem as "MrButtermaker". The obsidian is in the negatives as well. 

Here is my Config:
blocks:
  OBSIDIAN:
    durability: 4
world-options:
  disable-bedrock-floor:
    - world
  disable-bedrock-roof:
    - world_nether
durability-material-checker: STICK
block-break-effect: MOBSPAWNER_FLAMES

Settings:
drop-blocks: true
water-protection: true

**Comment by LeeTheTech** [comment]
Issue should be resolved using 1.0.4 released today.
