### ISSUE TITLE
WaterProtection not working still

### ISSUE THREAD

**Issue by Thetduong** [SirLeezus/CrackedBlocks#5]
Currently on 1.17.1, and water protection is still not working when enabled/disabled. Blocks still take damage through water

**Comment by LeeTheTech** [comment]
I'll take a look soon!

**Comment by Thetduong** [comment]
> I'll take a look soon!

Alright thank you, I also sent you a picture on Spigot through our conversation to explain the issue better

**Comment by LeeTheTech** [comment]
Yeah, so I just tested it on 1.17.1, worked perfectly: 

Water protection on:
https://gyazo.com/3e3ce14e1afc7f4bf182e4f336b0a56b

Water protection off:
https://gyazo.com/cde771c2f1bced7f2ee19e7daa36c1b9

**Comment by Thetduong** [comment]
> Yeah, so I just tested it on 1.17.1, worked perfectly:
> 
> Water protection on:
> https://gyazo.com/3e3ce14e1afc7f4bf182e4f336b0a56b
> 
> Water protection off:
> https://gyazo.com/cde771c2f1bced7f2ee19e7daa36c1b9

https://gyazo.com/4af5a4afa596ddd0f6d322043b4e7e74

So the only obsidian that takes damage is the one below, so the TNT has to be above the obsidian and the obsidian blocks to the side of the TNT doesn't take damage (I tested with water-protection: true/false) and the bottom block always takes damage to TNT

**Comment by Thetduong** [comment]
So in the response above, The TNT directly below the explosion takes damage, but the obsidian beside it won't.

**Comment by LeeTheTech** [comment]
oh gotcha, I'll check this out soon

**Comment by LeeTheTech** [comment]
It's working: https://gyazo.com/86e005b89f45cf75cd2be2097d792dd7 The block just needs one water block connected to it.

**Comment by Thetduong** [comment]
In the gyazo you sent, it just proved that the explosion broke the obsidian below with water protection on. In vanilla no block would take damage if the explosion was in water.

Therefore, explosion above the obsidian even though it’s in water still damaged it and then eventually broke with water protection on which it shouldn’t do

**Comment by Zacymacy** [comment]
With the current version of cracked blocks, any block listed in the config.yml will take damage from creepers and tnt. I have tested this extensively and can verify that the issue is not fixed. Reopen the issue please

**Comment by LeeTheTech** [comment]
If you look in the gif I placed a tnt on that obsidian where no water block was connected. The way I designed it to work is if there is one water block connected to the block that's attempting to take a hit it won't count as a hit. 

Also, cracked blocks will take any explosion damage which is the way it's designed.

**Comment by Zacymacy** [comment]
What happened on my server is that a player made a base made out of obsidian and placed water on it. What happened was that another player was able to spam creeper eggs on the water above the obsidian and blow up the obsidian.

**Comment by LeeTheTech** [comment]
On second glance, there was one obsidian block that broke which was connected to water. I likely didn't check up or down, just N, S, E, W, I'll update that when I get home.

**Comment by LeeTheTech** [comment]
Try 1.0.7!

**Comment by Zacymacy** [comment]
Problem solved! Thank you.
