### ISSUE TITLE
Spawner Holographic Display

### ISSUE THREAD

**Issue by DanimalzCup** [SirLeezus/CrackedBlocks#6]
When a spawner is exploded with any type of explosion, the spawner drops at the correct durability however the holographic display of the mob spawner is still present. You have to place a spawner in the same spot and manually break it to remove it.

**Comment by LeeTheTech** [comment]
That would be an issue with whatever plugin is spawning that hologram (Armor Stand) above the spawner (That's not vanilla). You would want to use that plugin to add durability to spawners if it has a option for it.
