### ISSUE TITLE
Spawners

### ISSUE THREAD

**Issue by DanimalzCup** [SirLeezus/CrackedBlocks#7]
when placed on a spawner of mob type, when it explodes, you only get the regular spawner back (pig)

**Comment by Thetduong** [comment]
What spawner plugin are you using?

**Comment by DanimalzCup** [comment]
I am using ultimate stacker

**Comment by LeeTheTech** [comment]
This plugin does not have direct support for spawners currently, it would require a custom place block event along with the explosion event but that would be handled by this plugin, meaning any custom data that would come with ultimate stacker wouldn't work. I would highly suggest using their explosion handler for spawners if they have one, but I will likely add a toggle in the config soon for direct spawner support (for this plugin).

**Comment by LeeTheTech** [comment]
Turns out it would be best that the spawner plugin handles spawner explosions because normally they just break and if they have any custom meta data this plugin wouldn't know that unless it supported the spawner plugin directly, assuming it had a api.
