### ISSUE TITLE
Blocks (I.E. Obsidan) are breaking even though the TNT explosion is blocked by another block

### ISSUE THREAD

**Issue by Zacymacy** [SirLeezus/CrackedBlocks#8]
So I am doing some testing and I noticed that if obsidian (or any block listed in the config.yml of crackedblocks) is taking damage if the block is within the range of the primed TNT and ignores the fact that there is a water protected block blocking the primed TNT from damaging the obsidian.

So basically if obsidian is within the explosion radius and not touching any water, it will be damaged even though the TNT is not connected to that block.

I will attach some photos showing our testing methodology. The only blocks listed in our config and are used in out testing is OBSIDIAN & GRASS_BLOCK

We are also using STONE & GOLD_BLOCK to represent normal blocks because they are not listed in the config.yml of Cracked Blocks.

When the GOLD_BLOCK (or any normal block) is within the explosion radius but protected by another block that is water protected, it will not be damaged/destroyed. 

But if the block is OBSIDIAN, GRASS_BLOCK or any block in the config.yml, it will be damaged/destroyed even though it's in the same location.

![2021-09-23_10 26 08](https://user-images.githubusercontent.com/76797816/134556152-50d22066-ba5f-46cf-92b6-ee3cfcabbf48.png)
n
![2021-09-23_10 20 41](https://user-images.githubusercontent.com/76797816/134556155-b4677c62-b824-4af3-a270-c72112d3c9db.png)
![2021-09-23_10 23 37](https://user-images.githubusercontent.com/76797816/134556142-fadeb228-2492-4e21-b5cb-d65e38313ed2.png)
![2021-09-23_10 23 46](https://user-images.githubusercontent.com/76797816/134556146-f299055a-9c97-43d6-9ec0-75b59513bf7b.png)
n.

**Comment by Zacymacy** [comment]
I forgot to mention we are using Paper 1.17.1 and Cracked Blocks version 1.0.6

EDIT: I was still able to replicate the issue on version 1.0.7

**Comment by LeeTheTech** [comment]
Did you place the tnt or light it and it dropped? Because the way water protection works is one water block needs to be connected to the cracked block to not take a hit, if you placed it next to the obsidian the water block would have been removed.

**Comment by Zacymacy** [comment]
I tested by both placing the TNT under the water and lighting it and I also tested placing the TNT above the water and letting it fall. I was able to reproduce the issue in both scenarios. Also, the water source block was never destroyed by the placement of the TNT.

**Comment by LeeTheTech** [comment]
Well that's because it wouldn't be connected to a water block in your example, it only checks the block in question up, down, north, west, south, east. Your water is diangle, if you place the obsidian connected to a water block it should work correctly.
